### ISSUE TITLE
Dripline-Python to wrap Dripline-Cpp

### ISSUE THREAD

**Issue by nsoblath** [driplineorg/dripline#11]

**Comment by laroque** [comment]
We should use [pybind11](https://pybind11.readthedocs.io/en/stable/index.html) to provide a python interface to the behaviors implemented in dripline-cpp. This will allow us to maintain less total code and keep behaviors uniform.

Dripline-python will still exist and will contain the broad feature set that allows for rapid and concise development of control systems in python.

## Open questions:
- Should dripline-cpp still be a purely C++ library/repo which is a dependency/base image for dripline-python? If so, we'd presumably follow the [setuptools](https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-setuptools) build instructions to include the c++ source implementing the wrapping along side the python code which extends it. Alternatively, we could include the wrapping code in the dripline-cpp repo itself and follow the [cmake](https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-cmake) build instructions.

- What is the exact set of objects which need to be exposed to python? We should be able to omit some of the base classes wrap just those classes which will need to be used in python itself (this will likely include wrapping the param portion of scarab also).

**Comment by laroque** [comment]
Also, because I was asking about virtual functions, they seem to have that well in hand: https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python

**Comment by nsoblath** [comment]
The build example for CMake is running CMake through setuptools: https://github.com/pybind/cmake_example

I favor this solution since we have a CMake build for dripline-cpp and it should be easy to make a CMake build for dripline-python that uses dripline-cpp bas a submodule, based on the use of Pybind11 in Nymph.

**Comment by nsoblath** [comment]
This is currently being developed in dripline-python.

**Comment by nsoblath** [comment]
Closing the issue, as this is well underway with no roadblocks anticipated.
