### ISSUE TITLE
decide what `--verbosity` values should be (and maybe come up with a short-form, we use this often)

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline#26]

**Comment by laroque** [comment]
@nsoblath: some notes
* in python's `logging` library, the levels are:
DEBUG: 10
INFO: 20
WARNING: 30
ERROR: 40
CRITICAL: 50

The logger object handles anything >= the configured levels and you can log at intermediate integers if you specify the level explicitly.

The dragonfly behavior was to default the level to 25, then subtract 10 for each `-v` flag, so a single `-v` would add `INFO` and two adds everything. I have two questions then:
1) C++ macros have 3 levels below warning. As a practical matter, do we use that granularity (I feel like normally I want either silent or max output)? It could be an open item to add a PROG in python at level 25
2) What should the default level be (no extra CLI flags) and what should that user experience be? In python we support counting the number of times you pass `-v` to increment multiple levels. This is pretty consistent with many linux CLI tools, which I like, but conflicts with `-v --values` (how awful would it be to rename that or remove the short version to put `-v` on verbosity)? Alternately, we could have verbose (level 10) be default and support multiple `-q` to silence output.

**Comment by nsoblath** [comment]
Currently in Scarab, where these things are all defined, we have these logging levels:

* Trace: 0
* Debug: 1
* Info: 2
* Prog: 3
* Warn: 4
* Error: 5
* Fatal: 6

Items are logged if the level is >= the configured threshold.

Currently the way to change the verbosity at the command line is to use `--verbosity [uint]`.  There is no `-v` flag.

Answers to questions:

1. Katydid and psyllid use the Prog output level.  The original purpose was situations where you had some loop you were running (e.g. in Katydid, the loop over time slices), Info might print something brief each time through the loop, but Prog would suppress that and only print progress every X times through the loop.  This can be a pretty nice boost in performance when it matters.

2. I'm open to changing things in Scarab to matching the user experience in the Python code.  I think there would be little problem with changing the verbosity constants to match.  I should be able to add a `-v` flag with the option for specifying it multiple times to change the verbosity threshold.
