### ISSUE TITLE
Resolve build automation

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline#32]
Need to consistently see:
- running tests
- producing runtime artifacts (ie publishing container images and manifests)
- producing/publishing docs

Need to not see:
- timeout of arm image builds (proposal is staged builds)
- multiple jobs triggering and one failing when the other beats it to the publish step

**Comment by nsoblath** [comment]
This has largely been fixed by recent updates to GHA builds and moving documentation to RTD.  I'm going to close it for now.
