### ISSUE TITLE
global and/or user configurations

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline#5]
What do we think about the following?

## Context
Right now, our intended configuration looks something like this:
> (default values) -> (configuration file if passed) -> (command line non-option arguments)

This is a great logic for describing and updating the configuration of a particular service and its internal behavior.

There could be an orthogonal set of interests, however, which is to configure the behavior of the actual options. This is useful for configurations which are common to many/all services and allows user customization of behavior.  Some examples would be setting the default verbosity to be higher, defining the hostname of the AMQP broker, or storing credentials for connecting to the broker (or any other resources).

This behavior has previously been used in the so-called `project8_authentications.json` file, but that solution is not acceptable here.

## Proposal
I suggest a multi-tiered system, similar to the above, but which is local to a host rather than connected to a service:
> (default values) -> (/etc/dripline.conf) -> (~/.driplinerc) -> (command line options)

It may also be nice to follow the pattern of many newer tools and allow /etc/dripline.conf to specify a directory path (normally /etc/dripline.conf.d) which would allow the configuration elements of that file to be split into multiple files and grouped logically.

I'm not sure if it is desirable that the set of available configurations in the above files and those available on the CLI be exactly overlapping sets, or that either be a subset of the other. It is easy to imagine that these configuration files may contain blocks which are specific to either an implementation library (dripline-python or dripline-cpp), or an external resource (rabbitMQ or postgreSQL).

**Comment by laroque** [comment]
I believe that we (Noah and I) have agreed that we should proceed with a modified version of this. The procedure will be the following:

1) Whenever sensible classes will have default values.
2) We will define a system directory where configuration files should live. I suggest `/etc/dripline.d/` but am open to other suggestions. The authentication details for any remote service (database, amqp broker, etc.) should be stored in this directory but should *not* coexist in the same file. Whenever an instance of agent is generating its config, it should glob all .json files and use each to update the top-level configuration param-node.
3) The user may provide an authentication directory path with the `-a` flag, it is processed identically to the specific system path above, coming second so that it is possible to override system options.
4) Any CLI flags defined for the agent then update and override any of the above.

(This means that the `-a` flag needs to be processed before step 3, even though other flags will be processed after step 3 to override values set there).

Also, we should modify things so that scarab's authentication tool takes a path, and that dripline-cpp contains a hard-coded path of `/etc/dripline.d` (or something else if we prefer) which is passed to scarab. This allows the design to remain generic in scarab (maybe katydid wants to read from /var/lib/katydid etc.).

### Some further notes:
- the filenames must end in .json to be included
- the filenames themselves should match the remote service they access as a matter of convention, but should not actually be used
- the file should nest the configuration values in a dictionary with a single key naming the service, that way each file can be used to update an existing param_node with a result of just adding another key.


### Question:
How do we deal with a updating a nested structure? Consider a system-level file containing
`{ 'amqp': {"broker": "some-broker.domain"} }` and then a user-level config `{'amqp': { "username": "Alice" } } `. That is, I'm concerned about how we deal with the nesting in a way that the second round of files update rather than replacing the sub-sections.

From the perspective of the `agent` class and/or psyllid, is it reasonable that anything which may be used as a CLI flag could also be a top-level key in one of the above json files?

**Comment by nsoblath** [comment]
This is being closed for now in favor of the use of environment variables (see project8/scarab#63).
