### ISSUE TITLE
proposal: timestamps to higher precision

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline#6]
We decided to do this long ago but it was never put in place. The timestamps should go beyond second precision.

I suggest that every timestamp should include a decimal after the seconds, and zero or more digits after that (terminated by the Z indicating Zulu time).

Need to be sure that we're okay with variable size timestamps. The other option is to insist on zero-padding the values and then to decide how may digits we want to include. The prior issue I found is here (https://github.com/project8/dripline-python/issues/20) and it does not appear to clarify this point.

**Comment by nsoblath** [comment]
This is already how dripline-cpp works.  I don't think it was added as an intentional feature; it's just how the creation of the timestamp happens to work.

**Comment by nsoblath** [comment]
Documentation is included in branch feature/split_message

**Comment by nsoblath** [comment]
Merged to develop independently, commit b892dd7c1234c827bd3dfbaae80660c6ddab0820.
