### ISSUE TITLE
proposal: heartbeats

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline#7]
Would it be desirable to have either as a Use-Protocol requirement or as an established convention, regular heartbeats sent on the alerts exchange?

Benefits:
- monitoring there would allow one to see what is running and detect crashes
- could be used for service discovery, would need to think about actual use cases if any
- could eliminate the "pinger" patter, which has to be updated to include any new items
- could easily add logging of the last heartbeat from each unique service name, making it trivial to display what services are running on an interface website
- provides a short-term solution to failed pings due to long-blocking requests

Cons:
- there may exist failure modes whereby a service continues to heartbeat but is otherwise non-responsive... I don't think this is compelling, there could also be failure modes where ping responses can happen but other requests are non-responsive. Those failure modes, if observed, should be reported as bugs and treated

Other questions:
- What information should be included in the payload (if any):
  - some sort of counter? (if it resets, you know the service was restarted)
  - something else?
- Are there any Routing key terms we'd want beyond that it is a heartbeat and the service it comes from?

**Comment by laroque** [comment]
In discussion, we clarified that:

1. Heartbeat interval should be configured as a runtime option, but we should recommend a default (as we do with request timeouts)
2. Each service instance should create for itself a UUID (string)
3. Each heartbeat message be of type Alert, with a routing key target specified in the use protocol (just use `heartbeat`?)
4. Each heartbeat message payload should include:
    1. the service name: `name`
    2. the service instance uuid: `uuid`
    3. the service's heartbeat interval: `heartbeat_interval`

### Example
We can build a table with 5 columns (the 3 fields in the payload, plus a "first_heartbeat and a "last_heartbeat"). An alert handler service would then upsert on each heartbeat, either creating a new row if the UUID is new, or updating the last_heartbeat otherwise.

**Comment by nsoblath** [comment]
Branch for documenting this proposal: feature/heatbeat

**Comment by nsoblath** [comment]
Finished in dripline-cpp
